title: random stuff
description: foo bar

# https://docs.github.com/en/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll
# kramdown (default) or GFM - Github Flavored Markdown
# markdown: kramdown
markdown: GFM

